pipeline{
    agent{label 'master'}
    tools{maven 'Maven_home'}
    stages{
        stage('Checkout'){
          steps{
            git branch: 'master', url:'https://github.com/Aakanksha0906/Universityproject.git'
            }
        }
        stage('Build'){
          steps{
             bat 'cd University && mvn compile'
          }
        }
        stage('Test'){
          steps{
            bat 'cd University && mvn test'
            }
        }
        stage('Package'){
          steps{
            bat 'cd University && mvn package'
            }
        }
       
        stage('Deploy'){
           steps{
            bat 'start /b java -jar "C:/Program Files (x86)/Jenkins/workspace/University/University/target/University-0.0.1-SNAPSHOT.jar"'
            }
        }
    }
    
}
