pipeline{
    agent{label 'master'}
    tools{maven 'Maven_home'}
    stages{
        stage('Checkout'){
          steps{
            git branch: 'master', url:'https://github.com/Aakanksha0906/Universityproject.git'
            }
        }
        stage('Build'){
          steps{
             sh 'cd University && mvn compile -Dbuild.number=-${BUILD_NUMBER}'
          }
        }
        stage('Test'){
          steps{
            sh 'cd University && mvn test'
            }
        }
        stage('Package'){
          steps{
            sh 'cd University && mvn package'
            }
        }
       
        stage('Deploy'){
           steps{
            sh 'java -jar "/var/lib/jenkins/workspace/University/University/target/University-0.0.1-SNAPSHOT.jar"&'
            }
        }
        // Building Docker images
        stage('Building docker image') {
          steps{
             sh 'cd docker build -f Dockerfile -t univ' 
            
          }
        }
            // Running Docker container, make sure port 8005 is opened in 
        stage('Docker Run') {
            steps{
               sh 'sudo dockerImage.run -d -p 8005:8005  univ'
             }
          }
        
    }
        
    
}
