pipeline{
    agent{label 'master'}
    tools{maven 'Maven_home'}
    stages{
        stage('Checkout'){
          steps{
            git branch: 'master', url:'https://github.com/Aakanksha0906/Universityproject.git'
            }
        }
        stage('Build'){
          steps{
             sh 'cd University && mvn compile -Dbuild.number=-${BUILD_NUMBER}'
          }
        }
        stage('Test'){
          steps{
            sh 'cd University && mvn test'
            }
        }
        stage('Package'){
          steps{
            sh 'cd University && mvn package'
            }
        }
       
        stage('Deploy'){
           steps{
            sh 'java -jar "/var/lib/jenkins/workspace/University/University/target/University-0.0.1-SNAPSHOT.jar"&'
            }
        }
    }
        post {
            always {
                emailext body: 'A Test EMail', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: 'Test'
            }
        }
    
}
